# Generated by Django 2.1.2 on 2018-10-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='')),
                ('author', models.CharField(max_length=140)),
                ('contact_email', models.CharField(max_length=140)),
                ('contact_phone', models.CharField(max_length=140)),
            ],
        ),
    ]
