# Generated by Django 2.1.2 on 2018-11-12 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UploadPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.IntegerField(choices=[(1, 'Wintersport'), (2, 'Wassersport'), (3, 'Bergsport'), (4, 'Ballsport'), (5, 'Sonstiges')], default=1),
        ),
        migrations.AddField(
            model_name='article',
            name='location',
            field=models.TextField(default='76131 Karlsruhe', max_length=140),
        ),
        migrations.AddField(
            model_name='article',
            name='location_latitude',
            field=models.DecimalField(decimal_places=15, default=48.5, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='location_longitude',
            field=models.DecimalField(decimal_places=15, default='48.5', max_digits=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='None/no-img.jpg', upload_to='images'),
        ),
    ]
