# Generated by Django 2.1.2 on 2018-10-29 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadPage', '0002_auto_20181029_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
    ]
