# Generated by Django 2.1.2 on 2018-10-30 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UploadPage', '0004_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.IntegerField(choices=[(1, 'Wintersport'), (2, 'Wassersport'), (3, 'Bergsport'), (4, 'Ballsport'), (5, 'Sonstiges')], default=1),
        ),
    ]
