# Generated by Django 2.1.2 on 2018-11-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadPage', '0006_article_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='location',
            field=models.TextField(default='76131 Karlsruhe', max_length=140),
        ),
    ]
