# Generated by Django 2.1.2 on 2018-11-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadPage', '0007_auto_20181105_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='distance',
            field=models.IntegerField(default=999, max_length=24),
        ),
        migrations.AlterField(
            model_name='article',
            name='location',
            field=models.TextField(default='76131 Deutschland', max_length=140),
        ),
    ]
