# Generated by Django 2.1.2 on 2018-11-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadPage', '0008_auto_20181105_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='distance',
        ),
        migrations.AddField(
            model_name='article',
            name='location_horizontal',
            field=models.DecimalField(decimal_places=15, default=11.1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='location_vertical',
            field=models.DecimalField(decimal_places=15, default='48.5', max_digits=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='location',
            field=models.TextField(default='76131 Karlsruhe', max_length=140),
        ),
    ]
