# Generated by Django 2.1.2 on 2018-11-05 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadPage', '0009_auto_20181105_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='location_horizontal',
            new_name='location_latitude',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='location_vertical',
            new_name='location_longitude',
        ),
    ]
